// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAm59K_Uod2BpQBMupn88TTDcgf5dTpeM',
    appId: '1:663267627843:web:951519612504088f7a55f6',
    messagingSenderId: '663267627843',
    projectId: 'milktea-shop-45591',
    authDomain: 'milktea-shop-45591.firebaseapp.com',
    storageBucket: 'milktea-shop-45591.firebasestorage.app',
    measurementId: 'G-ZRCJDXPMXS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmYe6Mhskc59VTIrfl1Y3FD725lFwKEY',
    appId: '1:663267627843:ios:33c2c9dec40f22567a55f6',
    messagingSenderId: '663267627843',
    projectId: 'milktea-shop-45591',
    storageBucket: 'milktea-shop-45591.firebasestorage.app',
    iosBundleId: 'com.example.milkteaShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRmYe6Mhskc59VTIrfl1Y3FD725lFwKEY',
    appId: '1:663267627843:ios:33c2c9dec40f22567a55f6',
    messagingSenderId: '663267627843',
    projectId: 'milktea-shop-45591',
    storageBucket: 'milktea-shop-45591.firebasestorage.app',
    iosBundleId: 'com.example.milkteaShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAm59K_Uod2BpQBMupn88TTDcgf5dTpeM',
    appId: '1:663267627843:web:49d424a224ecc8357a55f6',
    messagingSenderId: '663267627843',
    projectId: 'milktea-shop-45591',
    authDomain: 'milktea-shop-45591.firebaseapp.com',
    storageBucket: 'milktea-shop-45591.firebasestorage.app',
    measurementId: 'G-6L34DVZGK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MqB2tgsMBhQBaRCerp2A2tkeN0OYwNI',
    appId: '1:663267627843:android:6a5f7589ccf154ac7a55f6',
    messagingSenderId: '663267627843',
    projectId: 'milktea-shop-45591',
    storageBucket: 'milktea-shop-45591.firebasestorage.app',
  );

}